/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

         Restaurant rest1 = new Restaurant("AL-ASALH RESTAURANT", 5, "JD");
        System.out.println(rest1);

        Review reviwe1 = new Review( "review 1", "tala", 2);
        System.out.println(reviwe1);

        Review review2 = new Review("review 2", "Bayan", 3);
        Review review3 = new Review("review 3", "Rana", 4);
        rest1.addReview(review2);
        rest1.addReview(review3);
        System.out.println(rest1);
    }


}
